# Feature selection

In [1]:
import os
import time
from math import log

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import display
from sklearn import metrics
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import Lasso, LassoCV
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from IPython.display import display

t = time.time()

In [2]:
df = pd.read_csv('data/df_train_prepro.csv').sample(frac=1)
df.shape

(1610494, 46)

In [3]:
columns_quant = ['contextid',
 'campaignctrlast24h',
 'dayssincelastvisitdouble',
 'ltf_nbglobaldisplay_4w',
 'ltf_nbpartnerdisplayssincelastclick',
 'ltf_nbpartnerdisplay_90d',
 'ltf_nbpartnerclick_90d',
 'ltf_nbpartnersales_90d',
 'nbdayssincelastclick',
 'nbdisplay_1hour',
 'nbdisplayglobalapprox_1d_sum_xdevice',
 'display_size',
 'zonecostineuro']

columns_cat = ['display_env',
            'target_env',
            'campaignscenario',
            'campaignvertical',
            'is_interstitial',
            'device_type']

X_quant = df[columns_quant]
X_quant_scaled = StandardScaler().fit_transform(X_quant)
print(len(X_quant.columns))
display(X_quant.columns)

X_cat = df[columns_cat]
X_cat = pd.get_dummies(X_cat, columns=columns_cat, drop_first=True)
X_cat_scaled = StandardScaler().fit_transform(X_cat)
print(len(X_cat.columns))
display(X_cat.columns)

X_quant_cat = df[columns_quant + columns_cat]
X_quant_cat = pd.get_dummies(X_quant_cat, columns=columns_cat, drop_first=True)
X_quant_cat_scaled = StandardScaler().fit_transform(X_quant_cat)
print(len(X_quant_cat.columns))
display(X_quant_cat.columns)

y = df['is_display_clicked']

13


Index(['contextid', 'campaignctrlast24h', 'dayssincelastvisitdouble',
       'ltf_nbglobaldisplay_4w', 'ltf_nbpartnerdisplayssincelastclick',
       'ltf_nbpartnerdisplay_90d', 'ltf_nbpartnerclick_90d',
       'ltf_nbpartnersales_90d', 'nbdayssincelastclick', 'nbdisplay_1hour',
       'nbdisplayglobalapprox_1d_sum_xdevice', 'display_size',
       'zonecostineuro'],
      dtype='object')

21


Index(['display_env_app_ios', 'display_env_other', 'display_env_web',
       'target_env_2', 'campaignscenario_5', 'campaignscenario_6',
       'campaignscenario_11', 'campaignscenario_12', 'campaignscenario_13',
       'campaignscenario_17', 'campaignvertical_20.0', 'campaignvertical_23.0',
       'campaignvertical_129.0', 'campaignvertical_200002.0',
       'is_interstitial_True', 'device_type_Desktop',
       'device_type_Desktop - Safari', 'device_type_Mobile - Other',
       'device_type_Unknown', 'device_type_iPad', 'device_type_iPhone'],
      dtype='object')

34


Index(['contextid', 'campaignctrlast24h', 'dayssincelastvisitdouble',
       'ltf_nbglobaldisplay_4w', 'ltf_nbpartnerdisplayssincelastclick',
       'ltf_nbpartnerdisplay_90d', 'ltf_nbpartnerclick_90d',
       'ltf_nbpartnersales_90d', 'nbdayssincelastclick', 'nbdisplay_1hour',
       'nbdisplayglobalapprox_1d_sum_xdevice', 'display_size',
       'zonecostineuro', 'display_env_app_ios', 'display_env_other',
       'display_env_web', 'target_env_2', 'campaignscenario_5',
       'campaignscenario_6', 'campaignscenario_11', 'campaignscenario_12',
       'campaignscenario_13', 'campaignscenario_17', 'campaignvertical_20.0',
       'campaignvertical_23.0', 'campaignvertical_129.0',
       'campaignvertical_200002.0', 'is_interstitial_True',
       'device_type_Desktop', 'device_type_Desktop - Safari',
       'device_type_Mobile - Other', 'device_type_Unknown', 'device_type_iPad',
       'device_type_iPhone'],
      dtype='object')

## Méthode LASSO

On choisit `fit_intercept=False` et `normalize=False` car les données sont déjà centrées et réduites.

In [4]:
def run_LassoCV(alphas_range, X, y, X_columns=False):
    lcv = LassoCV(alphas=alphas_range, normalize=False, fit_intercept=False, random_state=0, n_jobs=-1).fit(X, y)

    print(f"Best alpha : {lcv.alpha_}")

    lasso = Lasso(fit_intercept=False, normalize=False, alpha=lcv.alpha_)
    lasso.fit(X, y)
    
    if type(X_columns) == bool:
        X_columns = X.columns
    
    coeff_df = pd.DataFrame(np.transpose(lasso.coef_), X_columns, columns=['Coefficient abs']).abs()

    display(coeff_df.sort_values(by='Coefficient abs', ascending=False))

    print(f"\nNombre de coeffs non nuls : {len(coeff_df[coeff_df['Coefficient abs'] != 0])}")

### Variables quantitatives

In [5]:
%%time
alphas_range = np.linspace(0.001, 1, num=100)
print(alphas_range[:5])
run_LassoCV(alphas_range, X_quant_scaled, y, X_columns=X_quant.columns)

[0.001      0.01109091 0.02118182 0.03127273 0.04136364]
Best alpha : 0.001


Coefficient abs
zonecostineuro                               0.043662
display_size                                 0.023909
campaignctrlast24h                           0.023156
nbdisplay_1hour                              0.007687
nbdayssincelastclick                         0.003271
contextid                                    0.003043
ltf_nbpartnerclick_90d                       0.002896
nbdisplayglobalapprox_1d_sum_xdevice         0.002280
ltf_nbpartnerdisplayssincelastclick          0.000031
dayssincelastvisitdouble                     0.000000
ltf_nbglobaldisplay_4w                       0.000000
ltf_nbpartnerdisplay_90d                     0.000000
ltf_nbpartnersales_90d                       0.000000


Nombre de coeffs non nuls : 9
Wall time: 4.14 s


Le best alpha correspond à la borne inférieure de l'intervalle, nous continuons donc la recherche du best alpha.

In [6]:
%%time
alphas_range = np.linspace(0.000001, 0.002, num=100)
print(alphas_range[:5])
run_LassoCV(alphas_range, X_quant_scaled, y, X_columns=X_quant.columns)

[1.00000000e-06 2.11919192e-05 4.13838384e-05 6.15757576e-05
 8.17676768e-05]
Best alpha : 4.138383838383838e-05


Coefficient abs
zonecostineuro                               0.044530
display_size                                 0.024733
campaignctrlast24h                           0.024137
nbdisplay_1hour                              0.008331
ltf_nbpartnerclick_90d                       0.004725
nbdayssincelastclick                         0.004068
contextid                                    0.004039
nbdisplayglobalapprox_1d_sum_xdevice         0.003056
ltf_nbpartnerdisplay_90d                     0.001402
ltf_nbpartnersales_90d                       0.000738
ltf_nbpartnerdisplayssincelastclick          0.000349
ltf_nbglobaldisplay_4w                       0.000239
dayssincelastvisitdouble                     0.000075


Nombre de coeffs non nuls : 13
Wall time: 4.93 s


In [7]:
%%time
alphas_range = np.linspace(0.00001, 0.0001, num=100)
print(alphas_range[:5])
run_LassoCV(alphas_range, X_quant_scaled, y, X_columns=X_quant.columns)

[1.00000000e-05 1.09090909e-05 1.18181818e-05 1.27272727e-05
 1.36363636e-05]
Best alpha : 3.7272727272727276e-05


Coefficient abs
zonecostineuro                               0.044534
display_size                                 0.024736
campaignctrlast24h                           0.024141
nbdisplay_1hour                              0.008334
ltf_nbpartnerclick_90d                       0.004735
nbdayssincelastclick                         0.004072
contextid                                    0.004043
nbdisplayglobalapprox_1d_sum_xdevice         0.003059
ltf_nbpartnerdisplay_90d                     0.001415
ltf_nbpartnersales_90d                       0.000743
ltf_nbpartnerdisplayssincelastclick          0.000351
ltf_nbglobaldisplay_4w                       0.000250
dayssincelastvisitdouble                     0.000080


Nombre de coeffs non nuls : 13
Wall time: 5.02 s


Nous pouvons en conclure que la variable `dayssincelastvisitdouble` n'est pas utile.

### Variables quantitatives + catégorielles
On rajoute à présent les variables catégorielles.

In [8]:
%%time
alphas_range = np.linspace(0.001, 1, num=100)
print(alphas_range[:5])
run_LassoCV(alphas_range, X_quant_cat_scaled, y, X_columns=X_quant_cat.columns)

[0.001      0.01109091 0.02118182 0.03127273 0.04136364]
Best alpha : 0.001


Coefficient abs
is_interstitial_True                         0.039362
zonecostineuro                               0.036240
campaignctrlast24h                           0.016760
device_type_Desktop                          0.007656
display_size                                 0.007503
nbdisplay_1hour                              0.004086
nbdayssincelastclick                         0.003941
campaignscenario_13                          0.003517
device_type_iPhone                           0.002767
ltf_nbpartnerclick_90d                       0.002765
campaignvertical_200002.0                    0.002541
campaignscenario_12                          0.002278
device_type_iPad                             0.002065
device_type_Desktop - Safari                 0.002045
target_env_2                                 0.001745
display_env_app_ios                          0.001295
campaignscenario_17                          0.001014
nbdisplayglobalapprox_1d_sum_xdevice         0.000893
campaignvertical_23.0                        0.000525
dayssincelastvisitdouble                     0.000471
campaignscenario_5                           0.000352
device_type_Mobile - Other                   0.000326
campaignscenario_11                          0.000124
display_env_web                              0.000015
ltf_nbpartnerdisplayssincelastclick          0.000012
campaignscenario_6                           0.000000
campaignvertical_20.0                        0.000000
campaignvertical_129.0                       0.000000
display_env_other                            0.000000
ltf_nbpartnersales_90d                       0.000000
ltf_nbpartnerdisplay_90d                     0.000000
device_type_Unknown                          0.000000
ltf_nbglobaldisplay_4w                       0.000000
contextid                                    0.000000


Nombre de coeffs non nuls : 25
Wall time: 11 s


In [9]:
%%time
alphas_range = np.linspace(0.000001, 0.002, num=100)
print(alphas_range[:5])
run_LassoCV(alphas_range, X_quant_cat_scaled, y, X_columns=X_quant_cat.columns)

[1.00000000e-06 2.11919192e-05 4.13838384e-05 6.15757576e-05
 8.17676768e-05]
Best alpha : 1e-06


Coefficient abs
is_interstitial_True                         0.039164
zonecostineuro                               0.037140
campaignctrlast24h                           0.017124
device_type_Desktop                          0.009555
display_size                                 0.008221
device_type_iPhone                           0.006927
display_env_app_ios                          0.006209
target_env_2                                 0.005827
campaignscenario_13                          0.005017
nbdayssincelastclick                         0.004896
nbdisplay_1hour                              0.004730
ltf_nbpartnerclick_90d                       0.004555
campaignscenario_12                          0.004054
campaignvertical_200002.0                    0.003460
device_type_Desktop - Safari                 0.003304
campaignscenario_17                          0.002683
campaignscenario_5                           0.001956
device_type_iPad                             0.001782
campaignvertical_129.0                       0.001748
dayssincelastvisitdouble                     0.001694
campaignvertical_23.0                        0.001681
device_type_Mobile - Other                   0.001650
nbdisplayglobalapprox_1d_sum_xdevice         0.001466
ltf_nbpartnerdisplay_90d                     0.001364
campaignscenario_6                           0.001238
display_env_web                              0.000785
ltf_nbpartnersales_90d                       0.000691
campaignscenario_11                          0.000633
contextid                                    0.000613
ltf_nbpartnerdisplayssincelastclick          0.000437
campaignvertical_20.0                        0.000386
display_env_other                            0.000285
device_type_Unknown                          0.000262
ltf_nbglobaldisplay_4w                       0.000256


Nombre de coeffs non nuls : 34
Wall time: 17.3 s


In [10]:
%%time
alphas_range = np.linspace(0.000000001, 0.000002, num=100)
print(alphas_range[:5])
run_LassoCV(alphas_range, X_quant_cat_scaled, y, X_columns=X_quant_cat.columns)

[1.00000000e-09 2.11919192e-08 4.13838384e-08 6.15757576e-08
 8.17676768e-08]
Best alpha : 1e-09


Coefficient abs
is_interstitial_True                         0.039163
zonecostineuro                               0.037141
campaignctrlast24h                           0.017123
device_type_Desktop                          0.009557
display_size                                 0.008222
device_type_iPhone                           0.006931
display_env_app_ios                          0.006214
target_env_2                                 0.005831
campaignscenario_13                          0.005019
nbdayssincelastclick                         0.004897
nbdisplay_1hour                              0.004731
ltf_nbpartnerclick_90d                       0.004558
campaignscenario_12                          0.004056
campaignvertical_200002.0                    0.003461
device_type_Desktop - Safari                 0.003305
campaignscenario_17                          0.002685
campaignscenario_5                           0.001958
device_type_iPad                             0.001782
campaignvertical_129.0                       0.001750
dayssincelastvisitdouble                     0.001695
campaignvertical_23.0                        0.001684
device_type_Mobile - Other                   0.001652
nbdisplayglobalapprox_1d_sum_xdevice         0.001467
ltf_nbpartnerdisplay_90d                     0.001368
campaignscenario_6                           0.001241
display_env_web                              0.000786
ltf_nbpartnersales_90d                       0.000693
campaignscenario_11                          0.000633
contextid                                    0.000615
ltf_nbpartnerdisplayssincelastclick          0.000437
campaignvertical_20.0                        0.000387
display_env_other                            0.000286
device_type_Unknown                          0.000262
ltf_nbglobaldisplay_4w                       0.000259


Nombre de coeffs non nuls : 34
Wall time: 24.1 s


## Variance feature selection

In [11]:
def low_variance_feature_selection(X, threshold) :
    sel = VarianceThreshold(threshold)
    sel.fit(X)
    print(sel.get_support(indices=True))

    df = pd.DataFrame(sel.variances_, index=X.columns, columns=['Variance']).sort_values(by='Variance', ascending=False)

    display(df)

    return sel.transform(X)

In [12]:
low_variance_feature_selection(X_quant, 0.01)

[ 0  2  3  4  5  6  7  8  9 10 11 12]


Variance
display_size                          9.444482e+09
ltf_nbglobaldisplay_4w                2.607098e+04
ltf_nbpartnerdisplay_90d              1.061908e+04
nbdisplayglobalapprox_1d_sum_xdevice  4.449996e+03
dayssincelastvisitdouble              2.642414e+03
nbdayssincelastclick                  2.066988e+03
ltf_nbpartnerdisplayssincelastclick   7.590539e+02
nbdisplay_1hour                       7.176346e+01
zonecostineuro                        8.801236e+00
ltf_nbpartnerclick_90d                6.238911e+00
contextid                             5.835694e+00
ltf_nbpartnersales_90d                3.943017e+00
campaignctrlast24h                    1.537679e-05

array([[ 6.00000000e+00,  5.25260000e+01,  0.00000000e+00, ...,
         1.52291667e+01,  7.50000000e+04,  1.00199997e+00],
       [ 6.00000000e+00,  9.55000000e-01,  0.00000000e+00, ...,
         1.61322222e+01,  4.00000000e+00,  7.16162348e+00],
       [ 6.00000000e+00,  1.02140000e+01,  0.00000000e+00, ...,
         8.00000000e+00,  0.00000000e+00,  2.54258811e-02],
       ...,
       [ 6.00000000e+00,  1.22880000e+01,  0.00000000e+00, ...,
         5.86554630e+01,  0.00000000e+00,  1.18774921e-01],
       [ 6.00000000e+00,  6.19200000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  1.53600000e+05,  1.57291842e+00],
       [ 1.00000000e+00, -1.00000000e+00,  0.00000000e+00, ...,
         4.00000000e+00,  0.00000000e+00,  1.51292443e+00]])

In [13]:
low_variance_feature_selection(X_cat, 0.01)

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 18 19 20]


Variance
campaignscenario_13           0.232464
device_type_Desktop           0.216539
campaignvertical_20.0         0.211358
display_env_web               0.207430
campaignscenario_12           0.113986
device_type_iPhone            0.103931
campaignvertical_129.0        0.102221
target_env_2                  0.093956
display_env_app_ios           0.082996
campaignscenario_6            0.060119
campaignvertical_200002.0     0.055267
is_interstitial_True          0.039408
campaignscenario_11           0.038004
campaignvertical_23.0         0.025245
device_type_Unknown           0.022993
device_type_iPad              0.019757
device_type_Desktop - Safari  0.019161
campaignscenario_5            0.017087
campaignscenario_17           0.014899
device_type_Mobile - Other    0.007270
display_env_other             0.000099

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

## Univariate feature selection

In [14]:
from scipy.stats.stats import pearsonr
def univariate_selection(X, y) :
    features = list(X)
    correlation = []
    significance = []
    for feature in features:
        correl = pearsonr(X[feature].values, y.values)
        correlation.append(correl[0])
        significance.append(correl[1])
    df = pd.DataFrame()
    df['feature'] = features
    df['correlation'] = correlation
    df['abs_correlation'] = np.abs(correlation)
    df['significance'] = significance
    df['significant'] = df['significance'] < 0.01 # Label those P<0.01
    df.sort_values(by='abs_correlation', ascending=False, inplace=True)
    return df

In [15]:
univariate_selection(X_quant, y)

feature  correlation  abs_correlation  \
12                        zonecostineuro     0.214615         0.214615   
11                          display_size     0.145901         0.145901   
1                     campaignctrlast24h     0.104729         0.104729   
9                        nbdisplay_1hour    -0.045473         0.045473   
10  nbdisplayglobalapprox_1d_sum_xdevice    -0.032693         0.032693   
8                   nbdayssincelastclick    -0.024608         0.024608   
6                 ltf_nbpartnerclick_90d     0.023766         0.023766   
2               dayssincelastvisitdouble    -0.022727         0.022727   
0                              contextid     0.021707         0.021707   
5               ltf_nbpartnerdisplay_90d     0.004920         0.004920   
4    ltf_nbpartnerdisplayssincelastclick    -0.004315         0.004315   
7                 ltf_nbpartnersales_90d     0.003757         0.003757   
3                 ltf_nbglobaldisplay_4w    -0.000167         0.000167   

     significance  significant  
12   0.000000e+00         True  
11   0.000000e+00         True  
1    0.000000e+00         True  
9    0.000000e+00         True  
10   0.000000e+00         True  
8   3.742619e-214         True  
6   6.851296e-200         True  
2   5.873928e-183         True  
0   4.346806e-167         True  
5    4.269942e-10         True  
4    4.341959e-08         True  
7    1.865353e-06         True  
3    8.321589e-01        False

In [16]:
univariate_selection(X_cat, y)

feature  correlation  abs_correlation   significance  \
14          is_interstitial_True     0.246777         0.246777   0.000000e+00   
2                display_env_web    -0.087985         0.087985   0.000000e+00   
3                   target_env_2     0.067383         0.067383   0.000000e+00   
15           device_type_Desktop    -0.059810         0.059810   0.000000e+00   
0            display_env_app_ios     0.056112         0.056112   0.000000e+00   
8            campaignscenario_13    -0.048137         0.048137   0.000000e+00   
9            campaignscenario_17     0.040227         0.040227   0.000000e+00   
19              device_type_iPad     0.034953         0.034953   0.000000e+00   
20            device_type_iPhone     0.023572         0.023572  1.145756e-196   
7            campaignscenario_12    -0.018978         0.018978  3.478621e-128   
16  device_type_Desktop - Safari    -0.014497         0.014497   1.341878e-75   
6            campaignscenario_11     0.010834         0.010834   5.173525e-43   
12        campaignvertical_129.0    -0.009968         0.009968   1.119823e-36   
4             campaignscenario_5    -0.009725         0.009725   5.399781e-35   
18           device_type_Unknown     0.007146         0.007146   1.207864e-19   
5             campaignscenario_6    -0.006902         0.006902   1.972046e-18   
17    device_type_Mobile - Other    -0.006784         0.006784   7.345106e-18   
11         campaignvertical_23.0     0.006173         0.006173   4.725063e-15   
13     campaignvertical_200002.0     0.003120         0.003120   7.518363e-05   
10         campaignvertical_20.0    -0.002163         0.002163   6.058524e-03   
1              display_env_other    -0.000569         0.000569   4.705716e-01   

    significant  
14         True  
2          True  
3          True  
15         True  
0          True  
8          True  
9          True  
19         True  
20         True  
7          True  
16         True  
6          True  
12         True  
4          True  
18         True  
5          True  
17         True  
11         True  
13         True  
10         True  
1         False

In [17]:
print(f"Temps d'exécution total : {time.strftime('%H:%M:%S', time.gmtime(time.time()-t))}")

Temps d'exécution total : 00:01:28
